[package]
name = "parser_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fancy-regex = "0.13.0"
regex = "1.10.2"
regex-syntax = "0.8.2"
